### ISSUE TITLE
Failed to load the textile-preview package

### ISSUE THREAD

**Issue by liumengjun** [muffinmad/atom-textile-preview#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [textile-preview](https://github.com/muffinmad/atom-textile-preview) package 0.1.2

### Stack Trace

Failed to load the textile-preview package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/textile-preview/lib/textile-preview.coffee:2:6)
    at /packages/textile-preview/lib/textile-preview.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:794:28
```

### Commands

```
     -0:20.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-material-syntax 0.4.6 
atom-ternjs 0.16.1 
autoclose-html 0.23.0 
color-picker 2.2.5 
compare-files 0.8.0 
docblockr 0.9.1 
editorconfig 2.0.5 
file-icons 2.0.15 
goto-last-edit 0.3.2 
hex 0.6.2 
javascript-snippets 1.2.1 
language-restructuredtext 1.0.2 
language-textile 0.2.0 
last-cursor-position 0.9.0 
minimap 4.25.7 
monokai 0.19.0 
php-cs-fixer 4.1.0 
pigments 0.37.0 
pretty-json 1.6.1 
rst-preview 1.3.1 
textile-preview 0.1.2 
```

**Comment by muffinmad** [comment]
Is reinstall "textile-preview" helps? I have same atom version and I was able to install and use textile preview throught apm and atom setting.

**Comment by liumengjun** [comment]
That's ok after reinstall. thx!
