### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by blekdushi** [muffinmad/atom-textile-preview#5]
Occurs occassionally when saving plantuml file and atom-textile-preview reloads the preview. Although not changing a single character, the error disappears after hitting ctrl+s a few times.

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [textile-preview](https://github.com/muffinmad/atom-textile-preview) package 0.1.2

### Stack Trace

Uncaught Error: UNKNOWN: unknown error, open 'C:\Users\User\AppData\Local\Temp\plantuml-preview\usecases.svg'

```
At fs.js:646

Error: UNKNOWN: unknown error, open 'C:\Users\User\AppData\Local\Temp\plantuml-preview\usecases.svg'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.writeFileSync (fs.js:1303:33)
    at Object.writeFileSync (/packages/textile-preview/node_modules/fs-plus/lib/fs-plus.js:288:17)
    at /packages/plantuml-preview/lib/plantuml-preview-view.coffee:324:16
    at exit (/packages/plantuml-preview/lib/plantuml-preview-view.coffee:340:7)
    at o (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:14:1037414)
    at e.bufferStream (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:14:1037502)
    at Socket.e.on (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:14:1036170)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
     -2:13.8.0 core:move-right (input.hidden-input)
     -2:11.8.0 core:save (input.hidden-input)
     -1:53.8.0 core:delete (input.hidden-input)
     -1:53.6.0 core:move-down (input.hidden-input)
     -1:53.5.0 core:move-left (input.hidden-input)
     -1:53.3.0 core:delete (input.hidden-input)
     -1:52.3.0 core:save (input.hidden-input)
  6x -1:30.2.0 core:move-up (input.hidden-input)
  9x -1:29.1.0 core:move-down (input.hidden-input)
  5x -1:28 core:move-up (input.hidden-input)
     -1:27 editor:move-to-end-of-screen-line (input.hidden-input)
  3x -1:25.2.0 core:backspace (input.hidden-input)
     -1:23.9.0 autocomplete-plus:confirm (input.hidden-input)
     -1:23.3.0 core:save (input.hidden-input)
     -1:22.6.0 core:move-down (input.hidden-input)
     -1:20.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
language-oracle 1.9.0 
language-plantuml 0.2.0 
language-textile 0.2.0 
plantuml-preview 0.12.9 
split-diff 1.5.3 
textile-preview 0.1.2 
```

**Comment by muffinmad** [comment]
There are only one mention of textile-preview in stack trace and it is node module. Maybe it's worth to create issue for plantuml-preview.
